### ISSUE TITLE
Figure generation

### ISSUE THREAD

**Issue by jahidhasanlinix** [senya-ashukha/simple-equivariant-gnn#2]
Hi, I try to generate the figure as like yours, but I couldn't do that. Would you like to tell me how can plot figure like yours, can you share the code for that please if available?

**Comment by senya-ashukha** [comment]
Hi @jahidhasanlinix, 

The image is from the original paper; You can likely rich authors by the e-mail pointed here https://arxiv.org/pdf/2102.09844.pdf;

```
Correspondence to: Victor Garcia Satorras <v.garciasatorras@uva.nl>, Emiel Hoogeboom
<e.hoogeboom@uva.nl>, Max Welling <m.welling@uva.nl>.
```

Arsenii
